os: linux
dist: trusty
sudo: required
language: cpp
compiler: gcc

env:
  global:
    - BUILD_CCACHE_DIR=~/build/ccache
    - BUILD_NINJA_DIR=~/build/ninja
  matrix:
    - BUILD=linux
    - BUILD=linux-gcc5
    - BUILD=linux-cuda
    - BUILD=linux-mkl
    - BUILD=linux-android

matrix:
  include:
    - env: BUILD=osx
      os: osx
      osx_image: xcode8.3
      compiler: clang
    - env: BUILD=osx-ios
      os: osx
      osx_image: xcode8.3
      compiler: clang
    - env: BUILD=osx-android
      os: osx
      osx_image: xcode8.3
      compiler: clang

cache:
  directories:
    - $BUILD_CCACHE_DIR
    - $BUILD_NINJA_DIR
    - $HOME/.ccache

before_install:
  - source .travis/setup.sh

install:
  - ./.travis/install.sh
  - ./.travis/build.sh

script:
  - ./.travis/test.sh
